---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/git-commit: "3077824f49f7ef3d31c7d6620b352eb8f88c5148"
    fabric8.io/iconUrl: "img/icons/camel.svg"
    fabric8.io/git-branch: "master"
  labels:
    expose: "true"
    provider: "fabric8"
    project: "demo02"
    version: "1.0"
    group: "org.mycompany"
  name: "demo02"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "demo02"
    provider: "fabric8"
    group: "org.mycompany"
